### ISSUE TITLE
incorrect English

### ISSUE THREAD

**Issue by willhoneywill** [Phantas0s/questions-job-interview#2]
have a meeting not do meetings

https://ell.stackexchange.com/questions/78618/to-do-a-meeting-or-to-make-a-meeting

**Comment by josemartos** [comment]
:parrot:

**Comment by Phantas0s** [comment]
Oooh I missed that all this time?

Thanks Will (and Jose of course for your interesting comment). Hope you're doing both fine!

I let you the massive pleasure to close the issue.

**Comment by willhoneywill** [comment]
🥇
